---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.5
before_install: gem install bundler -v 2.0.1
env:
   global:
    - BUNDLE_JOBS=4
    - RAILS_ENV=test
addons:
   apt_packages:
    - postgresql-contrib-9.6

